name: PR

on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: fe-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      configuration: development

  test:
    uses: ./.github/workflows/test.yml
