name: PR

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      configuration: development

  test:
    uses: ./.github/workflows/test.yml