name: Unit testing

<<<<<<< HEAD
on:
  workflow_call
=======
on: workflow_call
>>>>>>> 744128fece7893755f7ea44c390cbba52c27b3db

jobs:
  test:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    
=======

>>>>>>> 744128fece7893755f7ea44c390cbba52c27b3db
    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List node modules
        continue-on-error: true
        run: npm list

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Angular CLI
        run: |
          npm install -g @angular/cli@17

      - name: Restore modules
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          echo $NODE_OPTIONS
          npm install --frozen-lockfile

      - name: Test
<<<<<<< HEAD
        run: ng test
=======
        run: npm run test
>>>>>>> 744128fece7893755f7ea44c390cbba52c27b3db
